# Generated by Django 5.2.10 on 2026-03-20 18:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otryad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IshchiGuruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('otryad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guruhlar', to='my_app.otryad')),
            ],
        ),
        migrations.CreateModel(
            name='TrainChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asu_id', models.IntegerField(unique=True)),
                ('track_number', models.CharField(blank=True, max_length=10, null=True)),
                ('operation', models.CharField(blank=True, max_length=50, null=True)),
                ('train_number', models.CharField(max_length=50)),
                ('form_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sostav_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nazn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nlp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('received_at', models.DateTimeField()),
                ('type_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vagon_count', models.IntegerField(default=0)),
                ('udl_code', models.CharField(blank=True, max_length=20, null=True)),
                ('total_weight', models.IntegerField(default=0)),
                ('oxr_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lok_code', models.CharField(blank=True, max_length=10, null=True)),
                ('assignment_status', models.CharField(choices=[('free', "Bo'sh"), ('pending', 'Kutilmoqda'), ('confirmed', 'Biriktirilgan'), ('completed', 'Tugatildi')], default='free', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('uzb_comments', models.TextField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('tabel_raqami', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_boss', models.BooleanField(default=False)),
                ('viloyat', models.CharField(blank=True, max_length=100, null=True)),
                ('shahar_tuman', models.CharField(blank=True, max_length=100, null=True)),
                ('mahalla', models.CharField(blank=True, max_length=100, null=True)),
                ('kocha', models.CharField(blank=True, max_length=100, null=True)),
                ('uy_raqami', models.CharField(blank=True, max_length=20, null=True)),
                ('razryad', models.CharField(blank=True, max_length=10, null=True)),
                ('oklad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('activation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_working', models.BooleanField(default=False)),
                ('work_start_time', models.DateTimeField(blank=True, null=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.ishchiguruh')),
                ('otryad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.otryad')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_working', models.BooleanField(default=False)),
                ('work_start_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='my_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_index', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='pending', max_length=20)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.ishchiguruh')),
                ('otryad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.otryad')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='my_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat_videos/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='chat_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ishchiguruh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagon_number', models.CharField(max_length=20, verbose_name='Vagon raqami')),
                ('vagon_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turi')),
                ('cargo_weight', models.IntegerField(default=0, verbose_name='Yuk vazni (kg)')),
                ('cargo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuk nomi')),
                ('is_checked', models.BooleanField(default=False)),
                ('has_issue', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tartib_raqam', models.IntegerField()),
                ('vagon_identifikator', models.CharField(max_length=20, unique=True)),
                ('sequence_number', models.IntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagonlar', to='my_app.taskassignment')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='my_app.trainchain')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oklad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('norma_soati', models.FloatField(default=0)),
                ('ishlagan_soati', models.FloatField(default=0)),
                ('tungi_soati', models.FloatField(default=0)),
                ('bayram_soati', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
    ]
