# Generated by Django 5.2.10 on 2026-03-22 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_trainchain_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainchain',
            name='otryad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.otryad'),
        ),
    ]
