# Generated by Django 5.2.10 on 2026-03-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_trainchain_otryad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainchain',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.ishchiguruh'),
        ),
    ]
