# Generated by Django 5.2.10 on 2026-03-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_trainchain_guruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainchain',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_trains', to='my_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.userprofile'),
        ),
    ]
