# Generated by Django 5.2.10 on 2026-03-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_trainchain_assigned_workers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainchain',
            options={'ordering': ['-received_at'], 'verbose_name': 'Poyezd zanjiri', 'verbose_name_plural': 'Poyezdlar zanjiri'},
        ),
        migrations.RemoveField(
            model_name='trainchain',
            name='assigned_worker',
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_trains', to='my_app.userprofile', verbose_name='Biriktirilgan ishchilar'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='assignment_status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('pending', 'Kutilmoqda'), ('confirmed', 'Biriktirilgan'), ('completed', 'Tugatildi')], default='free', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='asu_id',
            field=models.IntegerField(unique=True, verbose_name='ASU ID'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='form_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Formakod'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains', to='my_app.ishchiguruh'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Ishlov berilgan'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='lok_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lokomotiv'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='nazn_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nazn'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='nlp_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SostNLP'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='operation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operatsiya'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='otryad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains', to='my_app.otryad'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='oxr_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ohrana'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='received_at',
            field=models.DateTimeField(verbose_name='Qabul qilingan vaqti'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='sostav_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sostav'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='Umumiy vazni'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='track_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Yo'l (Путь)"),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='train_number',
            field=models.CharField(max_length=50, verbose_name='Poyezd raqami'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='type_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='udl_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UDL'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='uzb_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='vagon_count',
            field=models.IntegerField(default=0, verbose_name='Vagonlar soni'),
        ),
    ]
