# Generated by Django 5.2.10 on 2026-03-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_trainchain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainchain',
            options={},
        ),
        migrations.RemoveField(
            model_name='trainchain',
            name='assigned_workers',
        ),
        migrations.AddField(
            model_name='trainchain',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trains', to='my_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='assignment_status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('pending', 'Kutilmoqda'), ('confirmed', 'Biriktirilgan'), ('completed', 'Tugatildi')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='asu_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='form_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.ishchiguruh'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='lok_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='nazn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='nlp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='operation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='otryad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.otryad'),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='oxr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='received_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='sostav_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='track_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='train_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='type_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='udl_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='uzb_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainchain',
            name='vagon_count',
            field=models.IntegerField(default=0),
        ),
    ]
